tas:
  - name: Shai Szulanski 
    email: 
  - name: Jeffrey Ling
    email: 
  - name: Samuel Cheng
    email: 
  - name: Ankit Gupta
    email: 
  - name: Aidi Zhang
    email: 
  - name: Lily Zhang
    email: 
  - name: Frances Ding
    email: 
  - name: Mark Goldstein
    email: 
  - name: Charles Liu
    email: 
  - name: Jeffrey Chang
    email: 
  - name: Fanney Zhu
    email: 
  - name: Christine Hwang
    email: 


dates: ["", "Jan. 24", "Jan. 26", "Jan. 27", "Jan. 30", "Jan. 31", "Feb. 2","Feb. 6", "Feb. 7", "Feb. 9",  "Feb. 14", "Feb. 16",
        "Feb. 21", "Feb. 23", "Feb. 28", "Mar. 2", "Mar. 7", "Mar. 9", "Mar. 21", 
        "Mar. 23", "Mar. 28", "Mar. 30", "Apr. 4", "Apr. 6", "Apr. 11", "Apr. 13", "Apr. 18", "Apr. 20", "Apr. 25"]


ohs:
  - time: Tue 8-10pm
    location: Quincy DH
  - time: Wed 6-8pm
    location: MD 119 / Second Floor
  - time: Thu 8-10pm
    location: Currier DH
  - time: Thu 8-10pm
    location: Eliot DH
  - time: Fri 10-Noon
    location: MD First Floor Lounge (one floor above ground!)

lectures:
  - topic: <a href="lectures/01-lectures-intro.pdf">Machine Learning</a>
    subtopic: 
    hw: 
    papers:
    section: 
    demos:
  - topic: Regression
    subtopic: <a href="lectures/02-lectures-lr.pdf">Linear Regression 1</a>
    hw: 
    papers: Bishop &sect; 3.1, Sklearn &sect; 3.1, 18.10
    section:
    demos: <a href="https://github.com/harvard-ml-courses/cs181-demos/blob/master/Regression.ipynb">Regression</a>
  - topic: 
    subtopic: Section 0  <a href="sections/Section_0.pdf">Math Review</a>
    hw: 
    papers: 
    section:
    demos:  
  - topic: 
    subtopic: Section 1 <a href="sections/section01-s17-student.pdf">Linear Reg (<a href="sections/section01-s17-final.pdf">sol</a>) </a>
    hw: 
    papers: 
    section:
    demos:  
  - topic: 
    subtopic: <a href="lectures/03-lectures-lr.pdf">Linear Regression 2</a>
    hw: T1 <a href="https://harvard-ml-courses.github.io/cs181-s17-homeworks/h1/homework1-regression.pdf">Regression</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117075">submit</a>)
    papers: Bishop &sect; 2.3, 3.1
    section:
    demos: <a href = "https://github.com/harvard-ml-courses/cs181-demos/blob/master/Gaussian.ipynb"> Gaussian </a> <a href = "https://github.com/harvard-ml-courses/cs181-demos/blob/master/BasisRegression.ipynb"> BasisRegression </a> 
  - topic: Model Regularization

    subtopic: <a href="lectures/04-lectures-modelselection-tmp.pdf">Model Selection</a>

    hw: 
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Section 2 <a href="sections/section02-s17-student.pdf">Model Selection</a> <a href="https://github.com/harvard-ml-courses/cs181-demos">(ipynb)</a> 
    hw: 
    papers:
    section:
    demos:
  - topic: 
    subtopic: <a href="lectures/05-lectures-blr.pdf">Bayesian Linear Regression</a>
    hw: P1 <a href="hw/practical1-regression.pdf">Regression</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117077">submit</a> | <a href="https://inclass.kaggle.com/c/cs181-regression-practical">kaggle</a>) 
    papers: Bishop &sect; 3.3
    section:
    demos: 
  - topic: Classification
    subtopic: <a href="lectures/06-lectures-class.pdf">Linear Classification</a>
    hw: 
    papers: Bishop &sect; 4.1, Sklearn &sect;  15.9
    section:
    demos: 
  - topic: 
    subtopic: <a href="lectures/07-lectures-class.pdf">Probabilistic Classification</a>
    hw: 
    papers: Bishop &sect; 4.2, 4.3, Sklearn &sect;  18.1, 29.24
    section:
    demos: 
  - topic: Neural Networks
    subtopic: <a href="lectures/08-lectures-nn1.pdf">Neural Networks 1</a>
    hw: 
    papers: Bishop &sect; 5.1-5.2
    section:
    demos: 
  - topic: 
    subtopic: <a href="lectures/09-lectures-nn2.pdf">Neural Networks 2</a>
    hw: T2 <a href="hw/homework2-classification.pdf">Classification</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117078">submit</a>)
    papers: Bishop &sect; 5.3
    section:
    demos: 
  - topic: Margin-Based Models
    subtopic: <a href="lectures/10-lectures-margin.pdf">Margin-Based Classification</a>
    hw: 
    papers:
    section:
    demos: 
  - topic: 
    subtopic: <a href="lectures/11-lectures-svm.pdf">Support Vector Machines</a>
    hw: P2 <a href="hw/practical2-classification">Classification</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117079">submit</a> | <a href="https://inclass.kaggle.com/c/cs-181-classification-practical">kaggle</a>)
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Midterm 1
    hw: 
    papers: 
    section:
    demos: 
  - topic: Topics 1
    subtopic: <a href="lectures/12-lectures-deeplearning.pdf">Deep Learning</a>
    hw: 
    papers:
    section:
    demos: 
  - topic: Unsupervised
    subtopic: Hierarchical Clustering, K-Means
    hw: 
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Mixture Models, EM
    hw: T3 <a href="hw/homework3-svm.pdf">SVMs</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117080">submit</a>)
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Topic Models
    hw: 
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Dimensionality Reduction
    hw: T4 <a href="">Clustering</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117081">submit</a>)
    papers:
    section:
    demos: 
  - topic: Graphical Models
    subtopic: HMMs
    hw: 
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Bayesian Networks
    hw: P3 <a href="">Unsupervised</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117083">submit</a> | <a href="https://inclass.kaggle.com/c/cs-181-unsupervised-practical">kaggle</a>) 
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Inference
    hw: 
    papers:
    section:
    demos: 
  - topic: Reinforcement Learning
    subtopic: MDP / Value and Policy Iteration
    hw: T5 <a href="">EM</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117082">submit</a>)
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Reinforcement Learning
    hw: 
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Deep RL 
    hw: 
    papers:
    section:
    demos: 
  - topic: Topics 2
    subtopic: Learning Theory
    hw: 
    papers:
    section:
    demos: 
  - topic: 
    subtopic: Midterm 2
    hw: P4 <a href="">RL</a> (<a href="https://canvas.harvard.edu/courses/21992/assignments/117084">submit</a> | <a href="https://inclass.kaggle.com/c/cs-181-rl-practical">kaggle</a>)
    papers:
    section:
    demos: 

